### ISSUE TITLE
[BUG] KeyError: 'answer' when running llama_lrp.py

### ISSUE THREAD

**Issue by Vanessa-Taing** [Tomsawyerhu/LRP4RAG#1]
Hi,

I am trying to run the code locally, and encountered an error: KeyError: 'answer'

I looked through the code and jsonl file it is trying to read, there is no key named "answer" in the file, checking back at the references of the key value there is none in the llama_lrp.py folder, so I tried removing the line
`"answer": json_line["source_info"]["answer"]`

The code worked, at least until it gets killed
```
1th token, token=<|begin_of_text|>, rank=105542
Killed
```

I am assuming the key answer is actually not needed, is there any impact of removing it? Thanks.

**Comment by Tomsawyerhu** [comment]
Thanks for correcting the mistake, just remove this line. Can you provide your experiment settings to help me figure out the mistake.

**Comment by Vanessa-Taing** [comment]
Here are the settings:
OS: Ubuntu WSL
CUDA Version: 12.2
Python 3.12.4

Setup/ Replication steps:
1. Git clone
2. cd to core
3. Modification to code line 9-15:
```
model_id = 'akjindal53244/Llama-3.1-Storm-8B-FP8-Dynamic'
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
max_length = 100000
prompt = "",
model = AutoModelForCausalLM.from_pretrained(model_id, local_files_only=True)
tokenizer = AutoTokenizer.from_pretrained(model_id)
attnlrp.register(model)
```
4. Run `python llama_lrp.py`

**Comment by Tomsawyerhu** [comment]
To use lrp, you must rewrite the plm code to fit it for lrp, you can follow the  [lxt](https://github.com/rachtibat/LRP-eXplains-Transformers) module.
